### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sandeep200109** [DebjitPramanick/Blockchain-Crowdfunding-App#1]
./src/App.js
Cannot find file: 'CrowdFunding.json' does not match the corresponding name on disk: '.\src\contracts\Crowdfunding.json'.
This error occurred during the build time and cannot be dismissed.

**Comment by DebjitPramanick** [comment]
@sandeep200109 modify the path by changing Crowdfunding.json to CrowdFunding.json. (Make the 'f' capital)

**Comment by sandeep200109** [comment]
Now I am facing another problem related to path address

**Comment by DebjitPramanick** [comment]
Can you upload a screenshot of your problem?

**Comment by sandeep200109** [comment]
I have already sent a image.

**Comment by sandeep200109** [comment]
[image: image.png]
This is error right now facing

**Comment by sandeep200109** [comment]
Can u please help me to setup the project

**Comment by DebjitPramanick** [comment]
Not able to see the screenshots you are sending. 
![Screenshot_20230217_212415](https://user-images.githubusercontent.com/73888326/219702239-33a750c3-09d5-404e-90f5-014c5e58997a.png)

**Comment by sandeep200109** [comment]
Can u send your your email id

**Comment by DebjitPramanick** [comment]
Let's continue on twitter or instagram. You can get the profile url from Github profile.

**Comment by sandeep200109** [comment]
Can you share your Instagram handle it shows me user has not found

**Comment by DebjitPramanick** [comment]
debjitpramanickk
